// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAm5x-AEyF0BJDMZgmVSlFGCcfFRYnF-g',
    appId: '1:588878470055:web:9c3d36b36348504606f482',
    messagingSenderId: '588878470055',
    projectId: 'musicapp-19ecb',
    authDomain: 'musicapp-19ecb.firebaseapp.com',
    storageBucket: 'musicapp-19ecb.appspot.com',
    measurementId: 'G-22SC6EY8L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC--jgPPfCmwpNLLlVofLQRUbfPkWOPEWM',
    appId: '1:588878470055:android:174b410ae849982c06f482',
    messagingSenderId: '588878470055',
    projectId: 'musicapp-19ecb',
    storageBucket: 'musicapp-19ecb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHcx0-WTKGYCe7rRvPdYvNnWdO6UUUP_g',
    appId: '1:588878470055:ios:886b654ed95089dd06f482',
    messagingSenderId: '588878470055',
    projectId: 'musicapp-19ecb',
    storageBucket: 'musicapp-19ecb.appspot.com',
    iosClientId: '588878470055-os2tspl8ttproi6lopm7loje0t2msptl.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicappFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHcx0-WTKGYCe7rRvPdYvNnWdO6UUUP_g',
    appId: '1:588878470055:ios:886b654ed95089dd06f482',
    messagingSenderId: '588878470055',
    projectId: 'musicapp-19ecb',
    storageBucket: 'musicapp-19ecb.appspot.com',
    iosClientId: '588878470055-os2tspl8ttproi6lopm7loje0t2msptl.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicappFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAm5x-AEyF0BJDMZgmVSlFGCcfFRYnF-g',
    appId: '1:588878470055:web:7fee02d69d6e217b06f482',
    messagingSenderId: '588878470055',
    projectId: 'musicapp-19ecb',
    authDomain: 'musicapp-19ecb.firebaseapp.com',
    storageBucket: 'musicapp-19ecb.appspot.com',
    measurementId: 'G-SR7JY5QNE4',
  );
}
